#!/bin/sh
# Este script corre el build process de gatsby del sitio moitorrijos y lo despliega en dokku

echo 'Starting Gatsby build...😻'
npm run build
echo 'Gatsby build done...✅'
sleep 5
cd public/
echo 'Deploying to SR Apps 🚀'
git add --all && git commit -m 'Update' && git push production master
sleep 5
echo 'Build Process Complete!✅🥳🕺🏻'