// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "staticSiteMailer",
            "endpoint": "https://lzsssd4mki.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:7d347150-ecae-4302-94c2-17741526fd43",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_c84qpHs8I",
    "aws_user_pools_web_client_id": "70qg5bri8s349gmc1p0mo7i78i",
    "oauth": {}
};


export default awsmobile;
